# travis-ci integration for KiBOM

dist: xenial

language: python

python:
  - 2.7
  - 3.7

install:
  - pip install -r test/requirements.txt
  - pip install wheel

addons:
  apt:
    update: true

before_install:
  - sudo apt-get install python3-pip python3-coverage python3-xlsxwriter

script:
  # Check Python code for style-guide 
  - flake8 .
  # Run the coverage tests 
  - bash ./run-tests.sh
  # Ensure the module can actually build
  - python setup.py bdist_wheel --universal

after_success:
  - coveralls